export const FETCHING_DATA_FROM_API = 'FETCHING_DATA_FROM_API'
export const FETCHING_DATA_API_SUCCESS = 'FETCHING_DATA_API_SUCCESS'
export const FETCHING_DATA_API_FAILURE = 'FETCHING_DATA_API_FAILURE'
